class CountryFilters {
  // TODO: Kazakhstan, Kuwait, Palestinian Territory, [Taiwan, Republic of China]

  Map<String, dynamic> filteredCountries = {
    "ALA Aland Islands": "",
    "American Samoa": "",
    "Anguilla": "",
    "Antarctica": "",
    "Aruba": "",
    "Bermuda": "",
    "Bouvet Island": "",
    "British Indian Ocean Territory": "",
    "British Virgin Islands": "",
    "Cape Verde": "",
    "Cayman Islands": "",
    "Christmas Island": "",
    "Cocos (Keeling) Islands": "",
    "Cook Islands": "",
    "Eritrea": "",
    "Falkland Islands (Malvinas)": "",
    "Faroe Islands": "",
    "French Guiana": "",
    "French Southern Territories": "",
    "Gibraltar": "",
    "Greenland": "",
    "Guadeloupe": "",
    "Guam": "",
    "Guernsey": "",
    "Heard and Mcdonald Islands": "",
    "Holy See (Vatican City State)": "",
    "Hong Kong, SAR China": "",
    "Isle of Man": "",
    "Jersey": "",
    "Kiribati": "",
    "Korea (North)": "",
    "Macao, SAR China": "",
    "Marshall Islands": "",
    "Martinique": "",
    "Mayotte": "",
    "Micronesia, Federated States of": "",
    "Montserrat": "",
    "Nauru": "",
    "Netherlands Antilles": "",
    "New Caledonia": "",
    "Niue": "",
    "Norfolk Island": "",
    "Northern Mariana Islands": "",
    "Palau": "",
    "Pitcairn": "",
    "Puerto Rico": "",
    "Réunion": "",
    "Saint Helena": "",
    "Saint Pierre and Miquelon": "",
    "Saint-Barthélemy": "",
    "Saint-Martin (French part)": "",
    "Samoa": "",
    "Solomon Islands": "",
    "South Georgia and the South Sandwich Islands": "",
    "Svalbard and Jan Mayen Islands": "",
    "Tokelau": "",
    "Tonga": "",
    "Turkmenistan": "",
    "Turks and Caicos Islands": "",
    "Tuvalu": "",
    "US Minor Outlying Islands": "",
    "Vanuatu": "",
    "Virgin Islands, US": "",
    "Wallis and Futuna Islands": "",
  };

  Map<String, dynamic> exceptionCountries = {"Australia": "", "China": ""};
}
